version: '3'

services:

  database1:
    image: mysql
    ports:
      - "3310:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=priya

  database2:
    image: mysql
    ports:
      - "3311:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=priya

  database3:
    image: mysql
    ports:
      - "3312:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=priya
      
